### ISSUE TITLE
建议：添加CDN反代加速功能

### ISSUE THREAD

**Issue by 201853910** [YukiCoco/YukiDrive#25]
众所周知，国际版OneDrive速度很慢。  
然后有人搞了使用服务器反代下载加速（大佬可以搜一下“OneIndex反代”）。  
但是之前测试过使用CDN来反代，也是OK的。（这是之前无意搜到的方法，很OK）  
但是无论是使用CDN，还是用主机搞反代，都需要修改站点的配置文件（添加sub_filter字段）  
然后有人就给我介绍了个这个玩意：oneindex-j  
这个玩意是oneindex的修改版，它自带反代加速服务（其实就是免去修改网站配置文件了）  

例如我使用sp.cdnweb.icu反代了xxx.sharepoint.com；sp-my.cdnweb.icu反代了xxx-my.sharepoint.com  
那么再将在线观看/下载时使用的xxx.sharepoint.com替换为反代域名，速度就会加快很多。  

那么：大佬能否也添加一个这个功能
**强烈建议！**

**Comment by YukiCoco** [comment]
近期更新

**Comment by 201853910** [comment]
哇，太谢谢了

**Comment by YukiCoco** [comment]
[已完成](https://github.com/YukiCoco/YukiDrive/commit/18ae8010835b837ae698475af240a2b1ce204479)
