### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by wangjason-1** [YukiCoco/YukiDrive#3]
大大能不能编译一个arm64的执行文件......

arm64用 arm的包运行出错
YukiDrive: cannot execute binary file

**Comment by YukiCoco** [comment]
arm 编译包本身就支持 arm64 ，如果无法运行可能是处于一下原因：
> ARM64 support requires Linux kernel 4.14 or higher. Some linux distributions satisfy this requirement while others don't. For example, Ubuntu 18.04 is supported but Ubuntu 16.04 doesn't.
